wget https://msmarco.blob.core.windows.net/msmarcoranking/triples.train.small.tar.gz
wget https://msmarco.blob.core.windows.net/msmarcoranking/collection.tar.gz
wget https://msmarco.blob.core.windows.net/msmarcoranking/queries.tar.gz
wget https://msmarco.blob.core.windows.net/msmarcoranking/qrels.train.tsv
wget https://msmarco.blob.core.windows.net/msmarcoranking/qrels.dev.tsv
wget https://msmarco.blob.core.windows.net/msmarcoranking/orcas-doctrain-qrels.tsv.gz
wget https://msmarco.blob.core.windows.net/msmarcoranking/orcas-doctrain-queries.tsv.gz
wget https://msmarco.blob.core.windows.net/msmarcoranking/top1000.dev.tar.gz
wget https://msmarco.blob.core.windows.net/msmarcoranking/top1000.eval.tar.gz